<!DOCTYPE html>
<html>
<body>

<p>请输入 5 - 10 之间的数字：</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">测试输入</button>
<p id="message"></p>

<script>
function myFunction() {
    var message, x;
    message = document.getElementById("message");
    message.innerHTML = "";
    x = document.getElementById("demo").value;
    try { 
        if(x == "") throw "空的";
         if(isNaN(x)) throw "不是数字";
         x = Number(x);
        if(x < 5) throw  "太小";
        if(x > 10) throw "太大";    // 如果使用了 throw ，那么就会使用用户跑出的对象作为err对象，内置的被覆盖了，就没有name 和 message属性

        // var a = toPrecision(500);    如果没有 throw 而报错，那么就会使用 JS 中内置的err对象，这个对象有两个属性:name 和 message
    }
    catch(err) {
        // message.innerHTML = "输入是 " + err.name+err.message;
        message.innerHTML = "输入是 " + err;
    }
}
</script>

</body>
</html> 